FROM php:7.2-apache

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

WORKDIR /var/www/html/

RUN apt-get update && apt-get install -y \
	unzip \
	libcurl4-openssl-dev \
	libxml2-dev -y \
	zlib1g-dev \
	&& docker-php-ext-install curl mbstring xml pdo soap intl zip pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


COPY ./src ./

RUN composer install
EXPOSE 80